services:
  fastapi:
    ports: !reset []
  fastapi-1:
    ports: !reset []
  fastapi-2:
    ports: !reset []
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: chat_system-nginx-ci:latest
    volumes: !reset []
    ports: !override
      - "18080:80"
  postgres:
    ports: !reset []
  redis:
    ports: !reset []
  rabbitmq:
    ports: !reset []